body_params: # (https://www.stereolabs.com/docs/body-tracking/using-body-tracking)
  detection_model: HUMAN_BODY_FAST              # HUMAN_BODY_FAST, HUMAN_BODY_MEDIUM, HUMAN_BODY_ACCURATE 
  enable_body_fitting: True                     # Enables the fitting process of each detected person
  body_format: BODY_38                          # BODY_18, BODY_34, BODY_38
                                                # (from 34 keypoints to 70 keypoints, enable_body_fitting must be True)
  enable_tracking: True                         # To track persons’ motion within their environment 
  image_sync: True
  enable_segmentation: False
  set_as_static: True
  set_floor_as_origin: True

body_runtime_params:
  measure3D_reference_frame: CAMERA              # WORLD, CAMERA
  detection_confidence_threshold: 40